server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config/"
          # search-locations: "file:///Users//alho//Code//udemy//Master-Microservice-SpringBoot//config"
        git:
          uri: "https://github.com/Course-Master-Microservices/bank-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
    key: "EG8T3FF0FDG345SF56SDG"
